spring:
  application:
    name: appserver
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: shrinkit-urls
    redis:
      host: localhost
      port: 6379
      password: password

grpc:
  client:
    keyGenerationService:
      address: 'discovery:///keygeneration'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiationType: plaintext

server:
  port: 8082

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}