spring:
  application:
    name: appserver
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: shrinkit-urls
    redis:
      host: localhost
      port: 6379
      password: password

logging:
  level:
    root: debug