spring:
  application:
    name: appserver
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: shrinkit-urls
    redis:
      host: localhost
      port: 6379
      password: password
  output:
    ansi:
      enabled: always

grpc:
  client:
    keyGenerationService:
      address: static://localhost:9090
      negotiationType: plaintext